INFO = {
    "pathmnist": {
        "python_class": "PathMNIST",
        "description": "The PathMNIST is based on a prior study for predicting survival from colorectal cancer histology slides, providing a dataset (NCT-CRC-HE-100K) of 100,000 non-overlapping image patches from hematoxylin & eosin stained histological images, and a test dataset (CRC-VAL-HE-7K) of 7,180 image patches from a different clinical center. The dataset is comprised of 9 types of tissues, resulting in a multi-class classification task. We resize the source images of 3×224×224 into 3×28×28, and split NCT-CRC-HE-100K into training and validation set with a ratio of 9:1. The CRC-VAL-HE-7K is treated as the test set.",
        "url": "https://zenodo.org/records/10519652/files/pathmnist.npz?download=1",
        "MD5": "a8b06965200029087d5bd730944a56c1",
        "url_64": "https://zenodo.org/records/10519652/files/pathmnist_64.npz?download=1",
        "MD5_64": "55aa9c1e0525abe5a6b9d8343a507616",
        "url_128": "https://zenodo.org/records/10519652/files/pathmnist_128.npz?download=1",
        "MD5_128": "ac42d08fb904d92c244187169d1fd1d9",
        "url_224": "https://zenodo.org/records/10519652/files/pathmnist_224.npz?download=1",
        "MD5_224": "2c51a510bcdc9cf8ddb2af93af1eadec",
        "task": "multi-class",
        "label": {
            "0": "adipose",
            "1": "background",
            "2": "debris",
            "3": "lymphocytes",
            "4": "mucus",
            "5": "smooth muscle",
            "6": "normal colon mucosa",
            "7": "cancer-associated stroma",
            "8": "colorectal adenocarcinoma epithelium",
        },
        "n_channels": 3,
        "n_samples": {"train": 89996, "val": 10004, "test": 7180},
        "license": "CC BY 4.0",
    },
    "chestmnist": {
        "python_class": "ChestMNIST",
        "description": "The ChestMNIST is based on the NIH-ChestXray14 dataset, a dataset comprising 112,120 frontal-view X-Ray images of 30,805 unique patients with the text-mined 14 disease labels, which could be formulized as a multi-label binary-class classification task. We use the official data split, and resize the source images of 1×1024×1024 into 1×28×28.",
        "url": "https://zenodo.org/records/10519652/files/chestmnist.npz?download=1",
        "MD5": "02c8a6516a18b556561a56cbdd36c4a8",
        "url_64": "https://zenodo.org/records/10519652/files/chestmnist_64.npz?download=1",
        "MD5_64": "9de6cd0b934ebb5b7426cfba5efbae16",
        "url_128": "https://zenodo.org/records/10519652/files/chestmnist_128.npz?download=1",
        "MD5_128": "db107e5590b27930b62dbaf558aebee3",
        "url_224": "https://zenodo.org/records/10519652/files/chestmnist_224.npz?download=1",
        "MD5_224": "45bd33e6f06c3e8cdb481c74a89152aa",
        "task": "multi-label, binary-class",
        "label": {
            "0": "atelectasis",
            "1": "cardiomegaly",
            "2": "effusion",
            "3": "infiltration",
            "4": "mass",
            "5": "nodule",
            "6": "pneumonia",
            "7": "pneumothorax",
            "8": "consolidation",
            "9": "edema",
            "10": "emphysema",
            "11": "fibrosis",
            "12": "pleural",
            "13": "hernia",
        },
        "n_channels": 1,
        "n_samples": {"train": 78468, "val": 11219, "test": 22433},
        "license": "CC BY 4.0",
    },
    "dermamnist": {
        "python_class": "DermaMNIST",
        "description": "The DermaMNIST is based on the HAM10000, a large collection of multi-source dermatoscopic images of common pigmented skin lesions. The dataset consists of 10,015 dermatoscopic images categorized as 7 different diseases, formulized as a multi-class classification task. We split the images into training, validation and test set with a ratio of 7:1:2. The source images of 3×600×450 are resized into 3×28×28.",
        "url": "https://zenodo.org/records/10519652/files/dermamnist.npz?download=1",
        "MD5": "0744692d530f8e62ec473284d019b0c7",
        "url_64": "https://zenodo.org/records/10519652/files/dermamnist_64.npz?download=1",
        "MD5_64": "b70a2f5635c6199aeaa28c31d7202e1f",
        "url_128": "https://zenodo.org/records/10519652/files/dermamnist_128.npz?download=1",
        "MD5_128": "2defd784463fa5243564e855ed717de1",
        "url_224": "https://zenodo.org/records/10519652/files/dermamnist_224.npz?download=1",
        "MD5_224": "8974907d8e169bef5f5b96bc506ae45d",
        "task": "multi-class",
        "label": {
            "0": "actinic keratoses and intraepithelial carcinoma",
            "1": "basal cell carcinoma",
            "2": "benign keratosis-like lesions",
            "3": "dermatofibroma",
            "4": "melanoma",
            "5": "melanocytic nevi",
            "6": "vascular lesions",
        },
        "n_channels": 3,
        "n_samples": {"train": 7007, "val": 1003, "test": 2005},
        "license": "CC BY-NC 4.0",
    },
    "octmnist": {
        "python_class": "OCTMNIST",
        "description": "The OCTMNIST is based on a prior dataset of 109,309 valid optical coherence tomography (OCT) images for retinal diseases. The dataset is comprised of 4 diagnosis categories, leading to a multi-class classification task. We split the source training set with a ratio of 9:1 into training and validation set, and use its source validation set as the test set. The source images are gray-scale, and their sizes are (384−1,536)×(277−512). We center-crop the images and resize them into 1×28×28.",
        "url": "https://zenodo.org/records/10519652/files/octmnist.npz?download=1",
        "MD5": "c68d92d5b585d8d81f7112f81e2d0842",
        "url_64": "https://zenodo.org/records/10519652/files/octmnist_64.npz?download=1",
        "MD5_64": "e229e9440236b774d9f0dfef9d07bdaf",
        "url_128": "https://zenodo.org/records/10519652/files/octmnist_128.npz?download=1",
        "MD5_128": "0a97e76651ace45c5d943ee3f65b63ae",
        "url_224": "https://zenodo.org/records/10519652/files/octmnist_224.npz?download=1",
        "MD5_224": "abc493b6d529d5de7569faaef2773ba3",
        "task": "multi-class",
        "label": {
            "0": "choroidal neovascularization",
            "1": "diabetic macular edema",
            "2": "drusen",
            "3": "normal",
        },
        "n_channels": 1,
        "n_samples": {"train": 97477, "val": 10832, "test": 1000},
        "license": "CC BY 4.0",
    },
    "pneumoniamnist": {
        "python_class": "PneumoniaMNIST",
        "description": "The PneumoniaMNIST is based on a prior dataset of 5,856 pediatric chest X-Ray images. The task is binary-class classification of pneumonia against normal. We split the source training set with a ratio of 9:1 into training and validation set and use its source validation set as the test set. The source images are gray-scale, and their sizes are (384−2,916)×(127−2,713). We center-crop the images and resize them into 1×28×28.",
        "url": "https://zenodo.org/records/10519652/files/pneumoniamnist.npz?download=1",
        "MD5": "28209eda62fecd6e6a2d98b1501bb15f",
        "url_64": "https://zenodo.org/records/10519652/files/pneumoniamnist_64.npz?download=1",
        "MD5_64": "8f4eceb4ccffa70c672198ea285246c6",
        "url_128": "https://zenodo.org/records/10519652/files/pneumoniamnist_128.npz?download=1",
        "MD5_128": "05b46931834c231683c68f40c47b2971",
        "url_224": "https://zenodo.org/records/10519652/files/pneumoniamnist_224.npz?download=1",
        "MD5_224": "d6a3c71de1b945ea11211b03746c1fe1",
        "task": "binary-class",
        "label": {"0": "normal", "1": "pneumonia"},
        "n_channels": 1,
        "n_samples": {"train": 4708, "val": 524, "test": 624},
        "license": "CC BY 4.0",
    },
    "retinamnist": {
        "python_class": "RetinaMNIST",
        "description": "The RetinaMNIST is based on the DeepDRiD challenge, which provides a dataset of 1,600 retina fundus images. The task is ordinal regression for 5-level grading of diabetic retinopathy severity. We split the source training set with a ratio of 9:1 into training and validation set, and use the source validation set as the test set. The source images of 3×1,736×1,824 are center-cropped and resized into 3×28×28.",
        "url": "https://zenodo.org/records/10519652/files/retinamnist.npz?download=1",
        "MD5": "bd4c0672f1bba3e3a89f0e4e876791e4",
        "url_64": "https://zenodo.org/records/10519652/files/retinamnist_64.npz?download=1",
        "MD5_64": "afda852cc34dcda56f86ad2b2457dbcc",
        "url_128": "https://zenodo.org/records/10519652/files/retinamnist_128.npz?download=1",
        "MD5_128": "e48e916a24454daf90583d4e6efb1a18",
        "url_224": "https://zenodo.org/records/10519652/files/retinamnist_224.npz?download=1",
        "MD5_224": "eae7e3b6f3fcbda4ae613ebdcbe35348",
        "task": "ordinal-regression",
        "label": {"0": "0", "1": "1", "2": "2", "3": "3", "4": "4"},
        "n_channels": 3,
        "n_samples": {"train": 1080, "val": 120, "test": 400},
        "license": "CC BY 4.0",
    },
    "breastmnist": {
        "python_class": "BreastMNIST",
        "description": "The BreastMNIST is based on a dataset of 780 breast ultrasound images. It is categorized into 3 classes: normal, benign, and malignant. As we use low-resolution images, we simplify the task into binary classification by combining normal and benign as positive and classifying them against malignant as negative. We split the source dataset with a ratio of 7:1:2 into training, validation and test set. The source images of 1×500×500 are resized into 1×28×28.",
        "url": "https://zenodo.org/records/10519652/files/breastmnist.npz?download=1",
        "MD5": "750601b1f35ba3300ea97c75c52ff8f6",
        "url_64": "https://zenodo.org/records/10519652/files/breastmnist_64.npz?download=1",
        "MD5_64": "742edef2a1fd1524b2efff4bd7ba9364",
        "url_128": "https://zenodo.org/records/10519652/files/breastmnist_128.npz?download=1",
        "MD5_128": "363e4b3f8d712e9b5de15470a2aaadf1",
        "url_224": "https://zenodo.org/records/10519652/files/breastmnist_224.npz?download=1",
        "MD5_224": "b56378a6eefa9fed602bb16d192d4c8b",
        "task": "binary-class",
        "label": {"0": "malignant", "1": "normal, benign"},
        "n_channels": 1,
        "n_samples": {"train": 546, "val": 78, "test": 156},
        "license": "CC BY 4.0",
    },
    "bloodmnist": {
        "python_class": "BloodMNIST",
        "description": "The BloodMNIST is based on a dataset of individual normal cells, captured from individuals without infection, hematologic or oncologic disease and free of any pharmacologic treatment at the moment of blood collection. It contains a total of 17,092 images and is organized into 8 classes. We split the source dataset with a ratio of 7:1:2 into training, validation and test set. The source images with resolution 3×360×363 pixels are center-cropped into 3×200×200, and then resized into 3×28×28.",
        "url": "https://zenodo.org/records/10519652/files/bloodmnist.npz?download=1",
        "MD5": "7053d0359d879ad8a5505303e11de1dc",
        "url_64": "https://zenodo.org/records/10519652/files/bloodmnist_64.npz?download=1",
        "MD5_64": "2b94928a2ae4916078ca51e05b6b800b",
        "url_128": "https://zenodo.org/records/10519652/files/bloodmnist_128.npz?download=1",
        "MD5_128": "adace1e0ed228fccda1f39692059dd4c",
        "url_224": "https://zenodo.org/records/10519652/files/bloodmnist_224.npz?download=1",
        "MD5_224": "b718ff6835fcbdb22ba9eacccd7b2601",
        "task": "multi-class",
        "label": {
            "0": "basophil",
            "1": "eosinophil",
            "2": "erythroblast",
            "3": "immature granulocytes(myelocytes, metamyelocytes and promyelocytes)",
            "4": "lymphocyte",
            "5": "monocyte",
            "6": "neutrophil",
            "7": "platelet",
        },
        "n_channels": 3,
        "n_samples": {"train": 11959, "val": 1712, "test": 3421},
        "license": "CC BY 4.0",
    },
    "tissuemnist": {
        "python_class": "TissueMNIST",
        "description": "We use the BBBC051, available from the Broad Bioimage Benchmark Collection. The dataset contains 236,386 human kidney cortex cells, segmented from 3 reference tissue specimens and organized into 8 categories. We split the source dataset with a ratio of 7:1:2 into training, validation and test set. Each gray-scale image is 32×32×7 pixels, where 7 denotes 7 slices. We take maximum values across the slices and resize them into 28×28 gray-scale images.",
        "url": "https://zenodo.org/records/10519652/files/tissuemnist.npz?download=1",
        "MD5": "ebe78ee8b05294063de985d821c1c34b",
        "url_64": "https://zenodo.org/records/10519652/files/tissuemnist_64.npz?download=1",
        "MD5_64": "123ece2eba09d0aa5d698fda57103344",
        "url_128": "https://zenodo.org/records/10519652/files/tissuemnist_128.npz?download=1",
        "MD5_128": "61b955355d7425a89687b06cca3ce0c2",
        "url_224": "https://zenodo.org/records/10519652/files/tissuemnist_224.npz?download=1",
        "MD5_224": "b077128c4a949f0a4eb01517f9037b9c",
        "task": "multi-class",
        "label": {
            "0": "Collecting Duct, Connecting Tubule",
            "1": "Distal Convoluted Tubule",
            "2": "Glomerular endothelial cells",
            "3": "Interstitial endothelial cells",
            "4": "Leukocytes",
            "5": "Podocytes",
            "6": "Proximal Tubule Segments",
            "7": "Thick Ascending Limb",
        },
        "n_channels": 1,
        "n_samples": {"train": 165466, "val": 23640, "test": 47280},
        "license": "CC BY 4.0",
    },
    "organamnist": {
        "python_class": "OrganAMNIST",
        "description": "The OrganAMNIST is based on 3D computed tomography (CT) images from Liver Tumor Segmentation Benchmark (LiTS). It is renamed from OrganMNIST_Axial (in MedMNIST v1) for simplicity. We use bounding-box annotations of 11 body organs from another study to obtain the organ labels. Hounsfield-Unit (HU) of the 3D images are transformed into gray-scale with an abdominal window. We crop 2D images from the center slices of the 3D bounding boxes in axial views (planes). The images are resized into 1×28×28 to perform multi-class classification of 11 body organs. 115 and 16 CT scans from the source training set are used as training and validation set, respectively. The 70 CT scans from the source test set are treated as the test set.",
        "url": "https://zenodo.org/records/10519652/files/organamnist.npz?download=1",
        "MD5": "68e3f8846a6bd62f0c9bf841c0d9eacc",
        "url_64": "https://zenodo.org/records/10519652/files/organamnist_64.npz?download=1",
        "MD5_64": "2dcccc29b88e6da5a01161ef20cda288",
        "url_128": "https://zenodo.org/records/10519652/files/organamnist_128.npz?download=1",
        "MD5_128": "eeae80d0a227a8d099027e1b3cfd3b60",
        "url_224": "https://zenodo.org/records/10519652/files/organamnist_224.npz?download=1",
        "MD5_224": "50747347e05c87dd3aaf92c49f9f3170",
        "task": "multi-class",
        "label": {
            "0": "bladder",
            "1": "femur-left",
            "2": "femur-right",
            "3": "heart",
            "4": "kidney-left",
            "5": "kidney-right",
            "6": "liver",
            "7": "lung-left",
            "8": "lung-right",
            "9": "pancreas",
            "10": "spleen",
        },
        "n_channels": 1,
        "n_samples": {"train": 34561, "val": 6491, "test": 17778},
        "license": "CC BY 4.0",
    },
    "organcmnist": {
        "python_class": "OrganCMNIST",
        "description": "The OrganCMNIST is based on 3D computed tomography (CT) images from Liver Tumor Segmentation Benchmark (LiTS). It is renamed from OrganMNIST_Coronal (in MedMNIST v1) for simplicity. We use bounding-box annotations of 11 body organs from another study to obtain the organ labels. Hounsfield-Unit (HU) of the 3D images are transformed into gray-scale with an abdominal window. We crop 2D images from the center slices of the 3D bounding boxes in coronal views (planes). The images are resized into 1×28×28 to perform multi-class classification of 11 body organs. 115 and 16 CT scans from the source training set are used as training and validation set, respectively. The 70 CT scans from the source test set are treated as the test set.",
        "url": "https://zenodo.org/records/10519652/files/organcmnist.npz?download=1",
        "MD5": "b9ceb9546e10131b32923c5bbeaea2b1",
        "url_64": "https://zenodo.org/records/10519652/files/organcmnist_64.npz?download=1",
        "MD5_64": "3ce34a8724ea6f548e6db4744d03b6a9",
        "url_128": "https://zenodo.org/records/10519652/files/organcmnist_128.npz?download=1",
        "MD5_128": "773c1f009daa3fe5d9a2a201b2a7ed94",
        "url_224": "https://zenodo.org/records/10519652/files/organcmnist_224.npz?download=1",
        "MD5_224": "050f5e875dc056f6768abf94ec9995d1",
        "task": "multi-class",
        "label": {
            "0": "bladder",
            "1": "femur-left",
            "2": "femur-right",
            "3": "heart",
            "4": "kidney-left",
            "5": "kidney-right",
            "6": "liver",
            "7": "lung-left",
            "8": "lung-right",
            "9": "pancreas",
            "10": "spleen",
        },
        "n_channels": 1,
        "n_samples": {"train": 12975, "val": 2392, "test": 8216},
        "license": "CC BY 4.0",
    },
    "organsmnist": {
        "python_class": "OrganSMNIST",
        "description": "The OrganSMNIST is based on 3D computed tomography (CT) images from Liver Tumor Segmentation Benchmark (LiTS). It is renamed from OrganMNIST_Sagittal (in MedMNIST v1) for simplicity. We use bounding-box annotations of 11 body organs from another study to obtain the organ labels. Hounsfield-Unit (HU) of the 3D images are transformed into gray-scale with an abdominal window. We crop 2D images from the center slices of the 3D bounding boxes in sagittal views (planes). The images are resized into 1×28×28 to perform multi-class classification of 11 body organs. 115 and 16 CT scans from the source training set are used as training and validation set, respectively. The 70 CT scans from the source test set are treated as the test set.",
        "url": "https://zenodo.org/records/10519652/files/organsmnist.npz?download=1",
        "MD5": "9ab87b696fb54e2a387ebe992d6ed5f1",
        "url_64": "https://zenodo.org/records/10519652/files/organsmnist_64.npz?download=1",
        "MD5_64": "53a6d115339d874c25e309a994ff46d3",
        "url_128": "https://zenodo.org/records/10519652/files/organsmnist_128.npz?download=1",
        "MD5_128": "ded0c5fa01a95dc4978b956f613e9b8e",
        "url_224": "https://zenodo.org/records/10519652/files/organsmnist_224.npz?download=1",
        "MD5_224": "b354719e553fbbb2513d5533f52a4cb1",
        "task": "multi-class",
        "label": {
            "0": "bladder",
            "1": "femur-left",
            "2": "femur-right",
            "3": "heart",
            "4": "kidney-left",
            "5": "kidney-right",
            "6": "liver",
            "7": "lung-left",
            "8": "lung-right",
            "9": "pancreas",
            "10": "spleen",
        },
        "n_channels": 1,
        "n_samples": {"train": 13932, "val": 2452, "test": 8827},
        "license": "CC BY 4.0",
    },
    "organmnist3d": {
        "python_class": "OrganMNIST3D",
        "description": "The source of the OrganMNIST3D is the same as that of the Organ{A,C,S}MNIST. Instead of 2D images, we directly use the 3D bounding boxes and process the images into 28×28×28 to perform multi-class classification of 11 body organs. The same 115 and 16 CT scans as the Organ{A,C,S}MNIST from the source training set are used as training and validation set, respectively, and the same 70 CT scans as the Organ{A,C,S}MNIST from the source test set are treated as the test set.",
        "url": "https://zenodo.org/records/10519652/files/organmnist3d.npz?download=1",
        "MD5": "a0c5a1ff56af4f155c46d46fbb45a2fe",
        "url_64": "https://zenodo.org/records/10519652/files/organmnist3d_64.npz?download=1",
        "MD5_64": "58a2205adf14a9d0a189cb06dc78bf10",
        "task": "multi-class",
        "label": {
            "0": "liver",
            "1": "kidney-right",
            "2": "kidney-left",
            "3": "femur-right",
            "4": "femur-left",
            "5": "bladder",
            "6": "heart",
            "7": "lung-right",
            "8": "lung-left",
            "9": "spleen",
            "10": "pancreas",
        },
        "n_channels": 1,
        "n_samples": {"train": 971, "val": 161, "test": 610},
        "license": "CC BY 4.0",
    },
    "nodulemnist3d": {
        "python_class": "NoduleMNIST3D",
        "description": "The NoduleMNIST3D is based on the LIDC-IDRI, a large public lung nodule dataset, containing images from thoracic CT scans. The dataset is designed for both lung nodule segmentation and 5-level malignancy classification task. To perform binary classification, we categorize cases with malignancy level 1/2 into negative class and 4/5 into positive class, ignoring the cases with malignancy level 3. We split the source dataset with a ratio of 7:1:2 into training, validation and test set, and center-crop the spatially normalized images (with a spacing of 1mm×1mm×1mm) into 28×28×28.",
        "url": "https://zenodo.org/records/10519652/files/nodulemnist3d.npz?download=1",
        "MD5": "8755a7e9e05a4d9ce80a24c3e7a256f3",
        "url_64": "https://zenodo.org/records/10519652/files/nodulemnist3d_64.npz?download=1",
        "MD5_64": "c47c5b7d457bf6332200d2ea6d64ecd8",
        "task": "binary-class",
        "label": {"0": "benign", "1": "malignant"},
        "n_channels": 1,
        "n_samples": {"train": 1158, "val": 165, "test": 310},
        "license": "CC BY 4.0",
    },
    "adrenalmnist3d": {
        "python_class": "AdrenalMNIST3D",
        "description": "The AdrenalMNIST3D is a new 3D shape classification dataset, consisting of shape masks from 1,584 left and right adrenal glands (i.e., 792 patients). Collected from Zhongshan Hospital Affiliated to Fudan University, each 3D shape of adrenal gland is annotated by an expert endocrinologist using abdominal computed tomography (CT), together with a binary classification label of normal adrenal gland or adrenal mass. Considering patient privacy, we do not provide the source CT scans, but the real 3D shapes of adrenal glands and their classification labels. We calculate the center of adrenal and resize the center-cropped 64mm×64mm×64mm volume into 28×28×28. The dataset is randomly split into training/validation/test set of 1,188/98/298 on a patient level.",
        "url": "https://zenodo.org/records/10519652/files/adrenalmnist3d.npz?download=1",
        "MD5": "bbd3c5a5576322bc4cdfea780653b1ce",
        "url_64": "https://zenodo.org/records/10519652/files/adrenalmnist3d_64.npz?download=1",
        "MD5_64": "17721accfe9fb005146a47d33bc54b2f",
        "task": "binary-class",
        "label": {"0": "normal", "1": "hyperplasia"},
        "n_channels": 1,
        "n_samples": {"train": 1188, "val": 98, "test": 298},
        "license": "CC BY 4.0",
    },
    "fracturemnist3d": {
        "python_class": "FractureMNIST3D",
        "description": "The FractureMNIST3D is based on the RibFrac Dataset, containing around 5,000 rib fractures from 660 computed tomography 153 (CT) scans. The dataset organizes detected rib fractures into 4 clinical categories (i.e., buckle, nondisplaced, displaced, and segmental rib fractures). As we use low-resolution images, we disregard segmental rib fractures and classify 3 types of rib fractures (i.e., buckle, nondisplaced, and displaced). For each annotated fracture area, we calculate its center and resize the center-cropped 64mm×64mm×64mm image into 28×28×28. The official split of training, validation and test set is used.",
        "url": "https://zenodo.org/records/10519652/files/fracturemnist3d.npz?download=1",
        "MD5": "6aa7b0143a6b42da40027a9dda61302f",
        "url_64": "https://zenodo.org/records/10519652/files/fracturemnist3d_64.npz?download=1",
        "MD5_64": "f01d7e6316aedf4210da0da5b7437b42",
        "task": "multi-class",
        "label": {
            "0": "buckle rib fracture",
            "1": "nondisplaced rib fracture",
            "2": "displaced rib fracture",
        },
        "n_channels": 1,
        "n_samples": {"train": 1027, "val": 103, "test": 240},
        "license": "CC BY 4.0",
    },
    "vesselmnist3d": {
        "python_class": "VesselMNIST3D",
        "description": "The VesselMNIST3D is based on an open-access 3D intracranial aneurysm dataset, IntrA, containing 103 3D models (meshes) of entire brain vessels collected by reconstructing MRA images. 1,694 healthy vessel segments and 215 aneurysm segments are generated automatically from the complete models. We fix the non-watertight mesh with PyMeshFix and voxelize the watertight mesh with trimesh into 28×28×28 voxels. We split the source dataset with a ratio of 7:1:2 into training, validation and test set.",
        "url": "https://zenodo.org/records/10519652/files/vesselmnist3d.npz?download=1",
        "MD5": "b41fd4f7e7e2feedddb201585ecafa1b",
        "url_64": "https://zenodo.org/records/10519652/files/vesselmnist3d_64.npz?download=1",
        "MD5_64": "6bb274a8846e1097066dcd64e2c4520f",
        "task": "binary-class",
        "label": {"0": "vessel", "1": "aneurysm"},
        "n_channels": 1,
        "n_samples": {"train": 1335, "val": 191, "test": 382},
        "license": "CC BY 4.0",
    },
    "synapsemnist3d": {
        "python_class": "SynapseMNIST3D",
        "description": "The SynapseMNIST3D is a new 3D volume dataset to classify whether a synapse is excitatory or inhibitory. It uses a 3D image volume of an adult rat acquired by a multi-beam scanning electron microscope. The original data is of the size 100×100×100um^3 and the resolution 8×8×30nm^3, where a (30um)^3 sub-volume was used in the MitoEM dataset with dense 3D mitochondria instance segmentation labels. Three neuroscience experts segment a pyramidal neuron within the whole volume and proofread all the synapses on this neuron with excitatory/inhibitory labels. For each labeled synaptic location, we crop a 3D volume of 1024×1024×1024nm^3 and resize it into 28×28×28 voxels. Finally, the dataset is randomly split with a ratio of 7:1:2 into training, validation and test set.",
        "url": "https://zenodo.org/records/10519652/files/synapsemnist3d.npz?download=1",
        "MD5": "1235b78a3cd6280881dd7850a78eadb6",
        "url_64": "https://zenodo.org/records/10519652/files/synapsemnist3d_64.npz?download=1",
        "MD5_64": "43bd14ebf3af9d3dd072446fedc14d5e",
        "task": "binary-class",
        "label": {"0": "inhibitory synapse", "1": "excitatory synapse"},
        "n_channels": 1,
        "n_samples": {"train": 1230, "val": 177, "test": 352},
        "license": "CC BY 4.0",
    },
    "imgnet1k": {
        "label": {0: 'tench',
                  1: 'goldfish',
                  2: 'great white shark',
                  3: 'tiger shark',
                  4: 'hammerhead',
                  5: 'electric ray',
                  6: 'stingray',
                  7: 'cock',
                  8: 'hen',
                  9: 'ostrich',
                  10: 'brambling',
                  11: 'goldfinch',
                  12: 'house finch',
                  13: 'junco',
                  14: 'indigo bunting',
                  15: 'robin',
                  16: 'bulbul',
                  17: 'jay',
                  18: 'magpie',
                  19: 'chickadee',
                  20: 'water ouzel',
                  21: 'kite',
                  22: 'bald eagle',
                  23: 'vulture',
                  24: 'great grey owl',
                  25: 'European fire salamander',
                  26: 'common newt',
                  27: 'eft',
                  28: 'spotted salamander',
                  29: 'axolotl',
                  30: 'bullfrog',
                  31: 'tree frog',
                  32: 'tailed frog',
                  33: 'loggerhead',
                  34: 'leatherback turtle',
                  35: 'mud turtle',
                  36: 'terrapin',
                  37: 'box turtle',
                  38: 'banded gecko',
                  39: 'common iguana',
                  40: 'American chameleon',
                  41: 'whiptail',
                  42: 'agama',
                  43: 'frilled lizard',
                  44: 'alligator lizard',
                  45: 'Gila monster',
                  46: 'green lizard',
                  47: 'African chameleon',
                  48: 'Komodo dragon',
                  49: 'African crocodile',
                  50: 'American alligator',
                  51: 'triceratops',
                  52: 'thunder snake',
                  53: 'ringneck snake',
                  54: 'hognose snake',
                  55: 'green snake',
                  56: 'king snake',
                  57: 'garter snake',
                  58: 'water snake',
                  59: 'vine snake',
                  60: 'night snake',
                  61: 'boa constrictor',
                  62: 'rock python',
                  63: 'Indian cobra',
                  64: 'green mamba',
                  65: 'sea snake',
                  66: 'horned viper',
                  67: 'diamondback',
                  68: 'sidewinder',
                  69: 'trilobite',
                  70: 'harvestman',
                  71: 'scorpion',
                  72: 'black and gold garden spider',
                  73: 'barn spider',
                  74: 'garden spider',
                  75: 'black widow',
                  76: 'tarantula',
                  77: 'wolf spider',
                  78: 'tick',
                  79: 'centipede',
                  80: 'black grouse',
                  81: 'ptarmigan',
                  82: 'ruffed grouse',
                  83: 'prairie chicken',
                  84: 'peacock',
                  85: 'quail',
                  86: 'partridge',
                  87: 'African grey',
                  88: 'macaw',
                  89: 'sulphur-crested cockatoo',
                  90: 'lorikeet',
                  91: 'coucal',
                  92: 'bee eater',
                  93: 'hornbill',
                  94: 'hummingbird',
                  95: 'jacamar',
                  96: 'toucan',
                  97: 'drake',
                  98: 'red-breasted merganser',
                  99: 'goose',
                  100: 'black swan',
                  101: 'tusker',
                  102: 'echidna',
                  103: 'platypus',
                  104: 'wallaby',
                  105: 'koala',
                  106: 'wombat',
                  107: 'jellyfish',
                  108: 'sea anemone',
                  109: 'brain coral',
                  110: 'flatworm',
                  111: 'nematode',
                  112: 'conch',
                  113: 'snail',
                  114: 'slug',
                  115: 'sea slug',
                  116: 'chiton',
                  117: 'chambered nautilus',
                  118: 'Dungeness crab',
                  119: 'rock crab',
                  120: 'fiddler crab',
                  121: 'king crab',
                  122: 'American lobster',
                  123: 'spiny lobster',
                  124: 'crayfish',
                  125: 'hermit crab',
                  126: 'isopod',
                  127: 'white stork',
                  128: 'black stork',
                  129: 'spoonbill',
                  130: 'flamingo',
                  131: 'little blue heron',
                  132: 'American egret',
                  133: 'bittern',
                  134: 'crane',
                  135: 'limpkin',
                  136: 'European gallinule',
                  137: 'American coot',
                  138: 'bustard',
                  139: 'ruddy turnstone',
                  140: 'red-backed sandpiper',
                  141: 'redshank',
                  142: 'dowitcher',
                  143: 'oystercatcher',
                  144: 'pelican',
                  145: 'king penguin',
                  146: 'albatross',
                  147: 'grey whale',
                  148: 'killer whale',
                  149: 'dugong',
                  150: 'sea lion',
                  151: 'Chihuahua',
                  152: 'Japanese spaniel',
                  153: 'Maltese dog',
                  154: 'Pekinese',
                  155: 'Shih-Tzu',
                  156: 'Blenheim spaniel',
                  157: 'papillon',
                  158: 'toy terrier',
                  159: 'Rhodesian ridgeback',
                  160: 'Afghan hound',
                  161: 'basset',
                  162: 'beagle',
                  163: 'bloodhound',
                  164: 'bluetick',
                  165: 'black-and-tan coonhound',
                  166: 'Walker hound',
                  167: 'English foxhound',
                  168: 'redbone',
                  169: 'borzoi',
                  170: 'Irish wolfhound',
                  171: 'Italian greyhound',
                  172: 'whippet',
                  173: 'Ibizan hound',
                  174: 'Norwegian elkhound',
                  175: 'otterhound',
                  176: 'Saluki',
                  177: 'Scottish deerhound',
                  178: 'Weimaraner',
                  179: 'Staffordshire bullterrier',
                  180: 'American Staffordshire terrier',
                  181: 'Bedlington terrier',
                  182: 'Border terrier',
                  183: 'Kerry blue terrier',
                  184: 'Irish terrier',
                  185: 'Norfolk terrier',
                  186: 'Norwich terrier',
                  187: 'Yorkshire terrier',
                  188: 'wire-haired fox terrier',
                  189: 'Lakeland terrier',
                  190: 'Sealyham terrier',
                  191: 'Airedale',
                  192: 'cairn',
                  193: 'Australian terrier',
                  194: 'Dandie Dinmont',
                  195: 'Boston bull',
                  196: 'miniature schnauzer',
                  197: 'giant schnauzer',
                  198: 'standard schnauzer',
                  199: 'Scotch terrier',
                  200: 'Tibetan terrier',
                  201: 'silky terrier',
                  202: 'soft-coated wheaten terrier',
                  203: 'West Highland white terrier',
                  204: 'Lhasa',
                  205: 'flat-coated retriever',
                  206: 'curly-coated retriever',
                  207: 'golden retriever',
                  208: 'Labrador retriever',
                  209: 'Chesapeake Bay retriever',
                  210: 'German short-haired pointer',
                  211: 'vizsla',
                  212: 'English setter',
                  213: 'Irish setter',
                  214: 'Gordon setter',
                  215: 'Brittany spaniel',
                  216: 'clumber',
                  217: 'English springer',
                  218: 'Welsh springer spaniel',
                  219: 'cocker spaniel',
                  220: 'Sussex spaniel',
                  221: 'Irish water spaniel',
                  222: 'kuvasz',
                  223: 'schipperke',
                  224: 'groenendael',
                  225: 'malinois',
                  226: 'briard',
                  227: 'kelpie',
                  228: 'komondor',
                  229: 'Old English sheepdog',
                  230: 'Shetland sheepdog',
                  231: 'collie',
                  232: 'Border collie',
                  233: 'Bouvier des Flandres',
                  234: 'Rottweiler',
                  235: 'German shepherd',
                  236: 'Doberman',
                  237: 'miniature pinscher',
                  238: 'Greater Swiss Mountain dog',
                  239: 'Bernese mountain dog',
                  240: 'Appenzeller',
                  241: 'EntleBucher',
                  242: 'boxer',
                  243: 'bull mastiff',
                  244: 'Tibetan mastiff',
                  245: 'French bulldog',
                  246: 'Great Dane',
                  247: 'Saint Bernard',
                  248: 'Eskimo dog',
                  249: 'malamute',
                  250: 'Siberian husky',
                  251: 'dalmatian',
                  252: 'affenpinscher',
                  253: 'basenji',
                  254: 'pug',
                  255: 'Leonberg',
                  256: 'Newfoundland',
                  257: 'Great Pyrenees',
                  258: 'Samoyed',
                  259: 'Pomeranian',
                  260: 'chow',
                  261: 'keeshond',
                  262: 'Brabancon griffon',
                  263: 'Pembroke',
                  264: 'Cardigan',
                  265: 'toy poodle',
                  266: 'miniature poodle',
                  267: 'standard poodle',
                  268: 'Mexican hairless',
                  269: 'timber wolf',
                  270: 'white wolf',
                  271: 'red wolf',
                  272: 'coyote',
                  273: 'dingo',
                  274: 'dhole',
                  275: 'African hunting dog',
                  276: 'hyena',
                  277: 'red fox',
                  278: 'kit fox',
                  279: 'Arctic fox',
                  280: 'grey fox',
                  281: 'tabby',
                  282: 'tiger cat',
                  283: 'Persian cat',
                  284: 'Siamese cat',
                  285: 'Egyptian cat',
                  286: 'cougar',
                  287: 'lynx',
                  288: 'leopard',
                  289: 'snow leopard',
                  290: 'jaguar',
                  291: 'lion',
                  292: 'tiger',
                  293: 'cheetah',
                  294: 'brown bear',
                  295: 'American black bear',
                  296: 'ice bear',
                  297: 'sloth bear',
                  298: 'mongoose',
                  299: 'meerkat',
                  300: 'tiger beetle',
                  301: 'ladybug',
                  302: 'ground beetle',
                  303: 'long-horned beetle',
                  304: 'leaf beetle',
                  305: 'dung beetle',
                  306: 'rhinoceros beetle',
                  307: 'weevil',
                  308: 'fly',
                  309: 'bee',
                  310: 'ant',
                  311: 'grasshopper',
                  312: 'cricket',
                  313: 'walking stick',
                  314: 'cockroach',
                  315: 'mantis',
                  316: 'cicada',
                  317: 'leafhopper',
                  318: 'lacewing',
                  319: 'dragonfly',
                  320: 'damselfly',
                  321: 'admiral',
                  322: 'ringlet',
                  323: 'monarch',
                  324: 'cabbage butterfly',
                  325: 'sulphur butterfly',
                  326: 'lycaenid',
                  327: 'starfish',
                  328: 'sea urchin',
                  329: 'sea cucumber',
                  330: 'wood rabbit',
                  331: 'hare',
                  332: 'Angora',
                  333: 'hamster',
                  334: 'porcupine',
                  335: 'fox squirrel',
                  336: 'marmot',
                  337: 'beaver',
                  338: 'guinea pig',
                  339: 'sorrel',
                  340: 'zebra',
                  341: 'hog',
                  342: 'wild boar',
                  343: 'warthog',
                  344: 'hippopotamus',
                  345: 'ox',
                  346: 'water buffalo',
                  347: 'bison',
                  348: 'ram',
                  349: 'bighorn',
                  350: 'ibex',
                  351: 'hartebeest',
                  352: 'impala',
                  353: 'gazelle',
                  354: 'Arabian camel',
                  355: 'llama',
                  356: 'weasel',
                  357: 'mink',
                  358: 'polecat',
                  359: 'black-footed ferret',
                  360: 'otter',
                  361: 'skunk',
                  362: 'badger',
                  363: 'armadillo',
                  364: 'three-toed sloth',
                  365: 'orangutan',
                  366: 'gorilla',
                  367: 'chimpanzee',
                  368: 'gibbon',
                  369: 'siamang',
                  370: 'guenon',
                  371: 'patas',
                  372: 'baboon',
                  373: 'macaque',
                  374: 'langur',
                  375: 'colobus',
                  376: 'proboscis monkey',
                  377: 'marmoset',
                  378: 'capuchin',
                  379: 'howler monkey',
                  380: 'titi',
                  381: 'spider monkey',
                  382: 'squirrel monkey',
                  383: 'Madagascar cat',
                  384: 'indri',
                  385: 'Indian elephant',
                  386: 'African elephant',
                  387: 'lesser panda',
                  388: 'giant panda',
                  389: 'barracouta',
                  390: 'eel',
                  391: 'coho',
                  392: 'rock beauty',
                  393: 'anemone fish',
                  394: 'sturgeon',
                  395: 'gar',
                  396: 'lionfish',
                  397: 'puffer',
                  398: 'abacus',
                  399: 'abaya',
                  400: 'academic gown',
                  401: 'accordion',
                  402: 'acoustic guitar',
                  403: 'aircraft carrier',
                  404: 'airliner',
                  405: 'airship',
                  406: 'altar',
                  407: 'ambulance',
                  408: 'amphibian',
                  409: 'analog clock',
                  410: 'apiary',
                  411: 'apron',
                  412: 'ashcan',
                  413: 'assault rifle',
                  414: 'backpack',
                  415: 'bakery',
                  416: 'balance beam',
                  417: 'balloon',
                  418: 'ballpoint',
                  419: 'Band Aid',
                  420: 'banjo',
                  421: 'bannister',
                  422: 'barbell',
                  423: 'barber chair',
                  424: 'barbershop',
                  425: 'barn',
                  426: 'barometer',
                  427: 'barrel',
                  428: 'barrow',
                  429: 'baseball',
                  430: 'basketball',
                  431: 'bassinet',
                  432: 'bassoon',
                  433: 'bathing cap',
                  434: 'bath towel',
                  435: 'bathtub',
                  436: 'beach wagon',
                  437: 'beacon',
                  438: 'beaker',
                  439: 'bearskin',
                  440: 'beer bottle',
                  441: 'beer glass',
                  442: 'bell cote',
                  443: 'bib',
                  444: 'bicycle-built-for-two',
                  445: 'bikini',
                  446: 'binder',
                  447: 'binoculars',
                  448: 'birdhouse',
                  449: 'boathouse',
                  450: 'bobsled',
                  451: 'bolo tie',
                  452: 'bonnet',
                  453: 'bookcase',
                  454: 'bookshop',
                  455: 'bottlecap',
                  456: 'bow',
                  457: 'bow tie',
                  458: 'brass',
                  459: 'brassiere',
                  460: 'breakwater',
                  461: 'breastplate',
                  462: 'broom',
                  463: 'bucket',
                  464: 'buckle',
                  465: 'bulletproof vest',
                  466: 'bullet train',
                  467: 'butcher shop',
                  468: 'cab',
                  469: 'caldron',
                  470: 'candle',
                  471: 'cannon',
                  472: 'canoe',
                  473: 'can opener',
                  474: 'cardigan',
                  475: 'car mirror',
                  476: 'carousel',
                  477: "carpenter's kit",
                  478: 'carton',
                  479: 'car wheel',
                  480: 'cash machine',
                  481: 'cassette',
                  482: 'cassette player',
                  483: 'castle',
                  484: 'catamaran',
                  485: 'CD player',
                  486: 'cello',
                  487: 'cellular telephone',
                  488: 'chain',
                  489: 'chainlink fence',
                  490: 'chain mail',
                  491: 'chain saw',
                  492: 'chest',
                  493: 'chiffonier',
                  494: 'chime',
                  495: 'china cabinet',
                  496: 'Christmas stocking',
                  497: 'church',
                  498: 'cinema',
                  499: 'cleaver',
                  500: 'cliff dwelling',
                  501: 'cloak',
                  502: 'clog',
                  503: 'cocktail shaker',
                  504: 'coffee mug',
                  505: 'coffeepot',
                  506: 'coil',
                  507: 'combination lock',
                  508: 'computer keyboard',
                  509: 'confectionery',
                  510: 'container ship',
                  511: 'convertible',
                  512: 'corkscrew',
                  513: 'cornet',
                  514: 'cowboy boot',
                  515: 'cowboy hat',
                  516: 'cradle',
                  517: 'crane',
                  518: 'crash helmet',
                  519: 'crate',
                  520: 'crib',
                  521: 'Crock Pot',
                  522: 'croquet ball',
                  523: 'crutch',
                  524: 'cuirass',
                  525: 'dam',
                  526: 'desk',
                  527: 'desktop computer',
                  528: 'dial telephone',
                  529: 'diaper',
                  530: 'digital clock',
                  531: 'digital watch',
                  532: 'dining table',
                  533: 'dishrag',
                  534: 'dishwasher',
                  535: 'disk brake',
                  536: 'dock',
                  537: 'dogsled',
                  538: 'dome',
                  539: 'doormat',
                  540: 'drilling platform',
                  541: 'drum',
                  542: 'drumstick',
                  543: 'dumbbell',
                  544: 'Dutch oven',
                  545: 'electric fan',
                  546: 'electric guitar',
                  547: 'electric locomotive',
                  548: 'entertainment center',
                  549: 'envelope',
                  550: 'espresso maker',
                  551: 'face powder',
                  552: 'feather boa',
                  553: 'file',
                  554: 'fireboat',
                  555: 'fire engine',
                  556: 'fire screen',
                  557: 'flagpole',
                  558: 'flute',
                  559: 'folding chair',
                  560: 'football helmet',
                  561: 'forklift',
                  562: 'fountain',
                  563: 'fountain pen',
                  564: 'four-poster',
                  565: 'freight car',
                  566: 'French horn',
                  567: 'frying pan',
                  568: 'fur coat',
                  569: 'garbage truck',
                  570: 'gasmask',
                  571: 'gas pump',
                  572: 'goblet',
                  573: 'go-kart',
                  574: 'golf ball',
                  575: 'golfcart',
                  576: 'gondola',
                  577: 'gong',
                  578: 'gown',
                  579: 'grand piano',
                  580: 'greenhouse',
                  581: 'grille',
                  582: 'grocery store',
                  583: 'guillotine',
                  584: 'hair slide',
                  585: 'hair spray',
                  586: 'half track',
                  587: 'hammer',
                  588: 'hamper',
                  589: 'hand blower',
                  590: 'hand-held computer',
                  591: 'handkerchief',
                  592: 'hard disc',
                  593: 'harmonica',
                  594: 'harp',
                  595: 'harvester',
                  596: 'hatchet',
                  597: 'holster',
                  598: 'home theater',
                  599: 'honeycomb',
                  600: 'hook',
                  601: 'hoopskirt',
                  602: 'horizontal bar',
                  603: 'horse cart',
                  604: 'hourglass',
                  605: 'iPod',
                  606: 'iron',
                  607: "jack-o'-lantern",
                  608: 'jean',
                  609: 'jeep',
                  610: 'jersey',
                  611: 'jigsaw puzzle',
                  612: 'jinrikisha',
                  613: 'joystick',
                  614: 'kimono',
                  615: 'knee pad',
                  616: 'knot',
                  617: 'lab coat',
                  618: 'ladle',
                  619: 'lampshade',
                  620: 'laptop',
                  621: 'lawn mower',
                  622: 'lens cap',
                  623: 'letter opener',
                  624: 'library',
                  625: 'lifeboat',
                  626: 'lighter',
                  627: 'limousine',
                  628: 'liner',
                  629: 'lipstick',
                  630: 'Loafer',
                  631: 'lotion',
                  632: 'loudspeaker',
                  633: 'loupe',
                  634: 'lumbermill',
                  635: 'magnetic compass',
                  636: 'mailbag',
                  637: 'mailbox',
                  638: 'maillot',
                  639: 'maillot',
                  640: 'manhole cover',
                  641: 'maraca',
                  642: 'marimba',
                  643: 'mask',
                  644: 'matchstick',
                  645: 'maypole',
                  646: 'maze',
                  647: 'measuring cup',
                  648: 'medicine chest',
                  649: 'megalith',
                  650: 'microphone',
                  651: 'microwave',
                  652: 'military uniform',
                  653: 'milk can',
                  654: 'minibus',
                  655: 'miniskirt',
                  656: 'minivan',
                  657: 'missile',
                  658: 'mitten',
                  659: 'mixing bowl',
                  660: 'mobile home',
                  661: 'Model T',
                  662: 'modem',
                  663: 'monastery',
                  664: 'monitor',
                  665: 'moped',
                  666: 'mortar',
                  667: 'mortarboard',
                  668: 'mosque',
                  669: 'mosquito net',
                  670: 'motor scooter',
                  671: 'mountain bike',
                  672: 'mountain tent',
                  673: 'mouse',
                  674: 'mousetrap',
                  675: 'moving van',
                  676: 'muzzle',
                  677: 'nail',
                  678: 'neck brace',
                  679: 'necklace',
                  680: 'nipple',
                  681: 'notebook',
                  682: 'obelisk',
                  683: 'oboe',
                  684: 'ocarina',
                  685: 'odometer',
                  686: 'oil filter',
                  687: 'organ',
                  688: 'oscilloscope',
                  689: 'overskirt',
                  690: 'oxcart',
                  691: 'oxygen mask',
                  692: 'packet',
                  693: 'paddle',
                  694: 'paddlewheel',
                  695: 'padlock',
                  696: 'paintbrush',
                  697: 'pajama',
                  698: 'palace',
                  699: 'panpipe',
                  700: 'paper towel',
                  701: 'parachute',
                  702: 'parallel bars',
                  703: 'park bench',
                  704: 'parking meter',
                  705: 'passenger car',
                  706: 'patio',
                  707: 'pay-phone',
                  708: 'pedestal',
                  709: 'pencil box',
                  710: 'pencil sharpener',
                  711: 'perfume',
                  712: 'Petri dish',
                  713: 'photocopier',
                  714: 'pick',
                  715: 'pickelhaube',
                  716: 'picket fence',
                  717: 'pickup',
                  718: 'pier',
                  719: 'piggy bank',
                  720: 'pill bottle',
                  721: 'pillow',
                  722: 'ping-pong ball',
                  723: 'pinwheel',
                  724: 'pirate',
                  725: 'pitcher',
                  726: 'plane',
                  727: 'planetarium',
                  728: 'plastic bag',
                  729: 'plate rack',
                  730: 'plow',
                  731: 'plunger',
                  732: 'Polaroid camera',
                  733: 'pole',
                  734: 'police van',
                  735: 'poncho',
                  736: 'pool table',
                  737: 'pop bottle',
                  738: 'pot',
                  739: "potter's wheel",
                  740: 'power drill',
                  741: 'prayer rug',
                  742: 'printer',
                  743: 'prison',
                  744: 'projectile',
                  745: 'projector',
                  746: 'puck',
                  747: 'punching bag',
                  748: 'purse',
                  749: 'quill',
                  750: 'quilt',
                  751: 'racer',
                  752: 'racket',
                  753: 'radiator',
                  754: 'radio',
                  755: 'radio telescope',
                  756: 'rain barrel',
                  757: 'recreational vehicle',
                  758: 'reel',
                  759: 'reflex camera',
                  760: 'refrigerator',
                  761: 'remote control',
                  762: 'restaurant',
                  763: 'revolver',
                  764: 'rifle',
                  765: 'rocking chair',
                  766: 'rotisserie',
                  767: 'rubber eraser',
                  768: 'rugby ball',
                  769: 'rule',
                  770: 'running shoe',
                  771: 'safe',
                  772: 'safety pin',
                  773: 'saltshaker',
                  774: 'sandal',
                  775: 'sarong',
                  776: 'sax',
                  777: 'scabbard',
                  778: 'scale',
                  779: 'school bus',
                  780: 'schooner',
                  781: 'scoreboard',
                  782: 'screen',
                  783: 'screw',
                  784: 'screwdriver',
                  785: 'seat belt',
                  786: 'sewing machine',
                  787: 'shield',
                  788: 'shoe shop',
                  789: 'shoji',
                  790: 'shopping basket',
                  791: 'shopping cart',
                  792: 'shovel',
                  793: 'shower cap',
                  794: 'shower curtain',
                  795: 'ski',
                  796: 'ski mask',
                  797: 'sleeping bag',
                  798: 'slide rule',
                  799: 'sliding door',
                  800: 'slot',
                  801: 'snorkel',
                  802: 'snowmobile',
                  803: 'snowplow',
                  804: 'soap dispenser',
                  805: 'soccer ball',
                  806: 'sock',
                  807: 'solar dish',
                  808: 'sombrero',
                  809: 'soup bowl',
                  810: 'space bar',
                  811: 'space heater',
                  812: 'space shuttle',
                  813: 'spatula',
                  814: 'speedboat',
                  815: 'spider web',
                  816: 'spindle',
                  817: 'sports car',
                  818: 'spotlight',
                  819: 'stage',
                  820: 'steam locomotive',
                  821: 'steel arch bridge',
                  822: 'steel drum',
                  823: 'stethoscope',
                  824: 'stole',
                  825: 'stone wall',
                  826: 'stopwatch',
                  827: 'stove',
                  828: 'strainer',
                  829: 'streetcar',
                  830: 'stretcher',
                  831: 'studio couch',
                  832: 'stupa',
                  833: 'submarine',
                  834: 'suit',
                  835: 'sundial',
                  836: 'sunglass',
                  837: 'sunglasses',
                  838: 'sunscreen',
                  839: 'suspension bridge',
                  840: 'swab',
                  841: 'sweatshirt',
                  842: 'swimming trunks',
                  843: 'swing',
                  844: 'switch',
                  845: 'syringe',
                  846: 'table lamp',
                  847: 'tank',
                  848: 'tape player',
                  849: 'teapot',
                  850: 'teddy',
                  851: 'television',
                  852: 'tennis ball',
                  853: 'thatch',
                  854: 'theater curtain',
                  855: 'thimble',
                  856: 'thresher',
                  857: 'throne',
                  858: 'tile roof',
                  859: 'toaster',
                  860: 'tobacco shop',
                  861: 'toilet seat',
                  862: 'torch',
                  863: 'totem pole',
                  864: 'tow truck',
                  865: 'toyshop',
                  866: 'tractor',
                  867: 'trailer truck',
                  868: 'tray',
                  869: 'trench coat',
                  870: 'tricycle',
                  871: 'trimaran',
                  872: 'tripod',
                  873: 'triumphal arch',
                  874: 'trolleybus',
                  875: 'trombone',
                  876: 'tub',
                  877: 'turnstile',
                  878: 'typewriter keyboard',
                  879: 'umbrella',
                  880: 'unicycle',
                  881: 'upright',
                  882: 'vacuum',
                  883: 'vase',
                  884: 'vault',
                  885: 'velvet',
                  886: 'vending machine',
                  887: 'vestment',
                  888: 'viaduct',
                  889: 'violin',
                  890: 'volleyball',
                  891: 'waffle iron',
                  892: 'wall clock',
                  893: 'wallet',
                  894: 'wardrobe',
                  895: 'warplane',
                  896: 'washbasin',
                  897: 'washer',
                  898: 'water bottle',
                  899: 'water jug',
                  900: 'water tower',
                  901: 'whiskey jug',
                  902: 'whistle',
                  903: 'wig',
                  904: 'window screen',
                  905: 'window shade',
                  906: 'Windsor tie',
                  907: 'wine bottle',
                  908: 'wing',
                  909: 'wok',
                  910: 'wooden spoon',
                  911: 'wool',
                  912: 'worm fence',
                  913: 'wreck',
                  914: 'yawl',
                  915: 'yurt',
                  916: 'web site',
                  917: 'comic book',
                  918: 'crossword puzzle',
                  919: 'street sign',
                  920: 'traffic light',
                  921: 'book jacket',
                  922: 'menu',
                  923: 'plate',
                  924: 'guacamole',
                  925: 'consomme',
                  926: 'hot pot',
                  927: 'trifle',
                  928: 'ice cream',
                  929: 'ice lolly',
                  930: 'French loaf',
                  931: 'bagel',
                  932: 'pretzel',
                  933: 'cheeseburger',
                  934: 'hotdog',
                  935: 'mashed potato',
                  936: 'head cabbage',
                  937: 'broccoli',
                  938: 'cauliflower',
                  939: 'zucchini',
                  940: 'spaghetti squash',
                  941: 'acorn squash',
                  942: 'butternut squash',
                  943: 'cucumber',
                  944: 'artichoke',
                  945: 'bell pepper',
                  946: 'cardoon',
                  947: 'mushroom',
                  948: 'Granny Smith',
                  949: 'strawberry',
                  950: 'orange',
                  951: 'lemon',
                  952: 'fig',
                  953: 'pineapple',
                  954: 'banana',
                  955: 'jackfruit',
                  956: 'custard apple',
                  957: 'pomegranate',
                  958: 'hay',
                  959: 'carbonara',
                  960: 'chocolate sauce',
                  961: 'dough',
                  962: 'meat loaf',
                  963: 'pizza',
                  964: 'potpie',
                  965: 'burrito',
                  966: 'red wine',
                  967: 'espresso',
                  968: 'cup',
                  969: 'eggnog',
                  970: 'alp',
                  971: 'bubble',
                  972: 'cliff',
                  973: 'coral reef',
                  974: 'geyser',
                  975: 'lakeside',
                  976: 'promontory',
                  977: 'sandbar',
                  978: 'seashore',
                  979: 'valley',
                  980: 'volcano',
                  981: 'ballplayer',
                  982: 'groom',
                  983: 'scuba diver',
                  984: 'rapeseed',
                  985: 'daisy',
                  986: "yellow lady's slipper",
                  987: 'corn',
                  988: 'acorn',
                  989: 'hip',
                  990: 'buckeye',
                  991: 'coral fungus',
                  992: 'agaric',
                  993: 'gyromitra',
                  994: 'stinkhorn',
                  995: 'earthstar',
                  996: 'hen-of-the-woods',
                  997: 'bolete',
                  998: 'ear',
                  999: 'toilet tissue'}
    }
}